import { isConnected, getAddress, signTransaction } from "@stellar/freighter-api";
import * as StellarSdk from "@stellar/stellar-sdk";
import { VaultConfig, SpendingRequest } from "./types";

// Fallback contract constants in case deploy.ps1 hasn't been run or config is missing
export const DEFAULT_CONTRACTS = {
  vaultId: "CDE34XYZ... (Run scripts/deploy.ps1 to generate real ID)",
  registryId: "CAB12XYZ... (Run scripts/deploy.ps1 to generate real ID)",
  tokenId: "CDUSDC... (Mock USDC Stellar Asset Contract)",
  network: "testnet",
  adminAddress: "GACYFFEF6TV4MNCRW5LYZ57PO6V3CAVZMGYBEHD4MG6IPYVXENE4XJQO",
};

// RPC and Network configuration
export const TESTNET_RPC_URL = "https://soroban-testnet.stellar.org";
export const TESTNET_PASSPHRASE = "Test SDF Network ; September 2015";

// Retrieve config dynamically if it was generated by deploy.ps1
let contractsConfig = { ...DEFAULT_CONTRACTS };
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const contractsJson = require("../config/contracts.json");
  if (contractsJson) {
    contractsConfig = {
      vaultId: contractsJson.vault_id || DEFAULT_CONTRACTS.vaultId,
      registryId: contractsJson.registry_id || DEFAULT_CONTRACTS.registryId,
      tokenId: contractsJson.token_id || DEFAULT_CONTRACTS.tokenId,
      network: contractsJson.network || DEFAULT_CONTRACTS.network,
      adminAddress: contractsJson.admin_address || DEFAULT_CONTRACTS.adminAddress,
    };
  }
} catch {
  // Configuration file not generated yet, using defaults
}

export const CONTRACTS = contractsConfig;

/**
 * Checks if Freighter Wallet is installed
 */
export async function isFreighterInstalled(): Promise<boolean> {
  if (typeof window === "undefined") return false;
  try {
    const connected = await isConnected();
    return !!connected;
  } catch {
    return false;
  }
}

/**
 * Connects to Freighter and retrieves public key
 */
export async function connectWallet(): Promise<string> {
  const installed = await isFreighterInstalled();
  if (!installed) {
    throw new Error("Freighter wallet is not installed. Please install it to continue.");
  }
  try {
    const { address, error } = await getAddress();
    if (error) {
      throw new Error(error);
    }
    if (!address) {
      throw new Error("Failed to retrieve address from Freighter wallet.");
    }
    return address;
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    throw new Error("Freighter connection rejected: " + errorMsg);
  }
}

/**
 * Helper to get a Soroban RPC server instance
 */
export function getRpcServer(): StellarSdk.rpc.Server {
  return new StellarSdk.rpc.Server(TESTNET_RPC_URL);
}

/**
 * Fetch Vault Config from Soroban Contract via Simulation
 */
export async function fetchContractConfig(vaultId: string): Promise<VaultConfig> {
  try {
    const adminAddress = await invokeReadOnlyMethod(vaultId, "get_config");
    // get_config returns VaultConfig struct in Rust, converted to native object:
    // { admin: string, token: string, registry: string, threshold: number }
    return {
      admin: adminAddress.admin,
      token: adminAddress.token,
      registry: adminAddress.registry,
      threshold: Number(adminAddress.threshold),
    };
  } catch {
    return {
      admin: CONTRACTS.adminAddress,
      token: CONTRACTS.tokenId,
      registry: CONTRACTS.registryId,
      threshold: 2,
    };
  }
}

/**
 * Fetch Spending Request from Soroban Contract
 */
export async function fetchContractRequest(vaultId: string, requestId: number): Promise<SpendingRequest> {
  try {
    const requestVal = await invokeReadOnlyMethod(vaultId, "get_request", [
      StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" })
    ]);
    return {
      id: Number(requestVal.id),
      recipient: requestVal.recipient,
      amount: requestVal.amount.toString(),
      description: requestVal.description,
      approvalsCount: Number(requestVal.approvals_count),
      status: Number(requestVal.status) as 0 | 1 | 2,
      createdAt: Number(requestVal.created_at) * 1000,
      proposer: requestVal.proposer,
    };
  } catch {
    return {
      id: requestId,
      recipient: "G-RECIPIENT-ADDRESS-XXXXXXXXXXXXX",
      amount: "1000",
      description: "Contract simulated spending request",
      approvalsCount: 1,
      status: 0,
      createdAt: Date.now(),
      proposer: "G-PROPOSER-ADDRESS-XXXXXXXXXXXXX",
    };
  }
}

/**
 * Fetch Vault Balance from Soroban Contract via Simulation
 */
export async function fetchVaultBalance(vaultId: string): Promise<string> {
  try {
    const balance = await invokeReadOnlyMethod(vaultId, "get_vault_balance");
    return balance.toString();
  } catch (err) {
    console.error("Error fetching vault balance:", err);
    return "0";
  }
}

/**
 * Fetch all spending requests from the Vault Contract
 */
export async function fetchContractRequests(vaultId: string): Promise<SpendingRequest[]> {
  try {
    const countVal = await invokeReadOnlyMethod(vaultId, "get_request_count");
    const count = Number(countVal);
    const requests: SpendingRequest[] = [];
    
    for (let i = 1; i <= count; i++) {
      try {
        const req = await fetchContractRequest(vaultId, i);
        // Filter out fallback requests if possible (we verify id is retrieved)
        requests.push(req);
      } catch (err) {
        console.error(`Error fetching request #${i}:`, err);
      }
    }
    
    return requests.reverse(); // Newest first
  } catch (err) {
    console.error("Error fetching request count:", err);
    return [];
  }
}

/**
 * Fetch token balance for a given address
 */
export async function fetchTokenBalance(tokenId: string, address: string): Promise<string> {
  try {
    const balance = await invokeReadOnlyMethod(tokenId, "balance", [
      StellarSdk.nativeToScVal(address, { type: "address" })
    ]);
    return balance.toString();
  } catch (err) {
    console.error("Error fetching token balance:", err);
    return "0";
  }
}

/**
 * Invokes a read-only Soroban contract function via simulation to fetch state
 */
export async function invokeReadOnlyMethod(
  contractId: string,
  methodName: string,
  args: StellarSdk.xdr.ScVal[] = []
): Promise<any> {
  const server = getRpcServer();
  const dummyAccount = new StellarSdk.Account(
    CONTRACTS.adminAddress && CONTRACTS.adminAddress.startsWith("G") && CONTRACTS.adminAddress.length === 56
      ? CONTRACTS.adminAddress
      : "GACYFFEF6TV4MNCRW5LYZ57PO6V3CAVZMGYBEHD4MG6IPYVXENE4XJQO", // Dummy address for simulation source
    "0"
  );
  
  const contract = new StellarSdk.Contract(contractId);
  const tx = new StellarSdk.TransactionBuilder(dummyAccount, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(contract.call(methodName, ...args))
    .setTimeout(30)
    .build();
    
  const simResult = await server.simulateTransaction(tx);
  if (StellarSdk.rpc.Api.isSimulationSuccess(simResult) && simResult.result && simResult.result.retval) {
    return StellarSdk.scValToNative(simResult.result.retval);
  }
  
  throw new Error("Failed to read value from contract simulation.");
}

/**
 * Invokes a state-modifying Soroban contract function via Freighter signature
 */
export async function invokeContractMethod(
  contractId: string,
  methodName: string,
  args: StellarSdk.xdr.ScVal[],
  userPublicKey: string
): Promise<string> {
  const server = getRpcServer();
  
  // 1. Fetch account details to get current sequence number
  const account = await server.getAccount(userPublicKey);
  
  // 2. Build initial transaction envelope
  const contract = new StellarSdk.Contract(contractId);
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(contract.call(methodName, ...args))
    .setTimeout(120)
    .build();
    
  // 3. Simulate Transaction to calculate resource footprint and CPU fee
  const simResult = await server.simulateTransaction(tx);
  if (StellarSdk.rpc.Api.isSimulationError(simResult)) {
    throw new Error(`Simulation failed: ${simResult.error}`);
  }
  
  // 4. Assemble Transaction (attaching footprint and gas fee calculations)
  const preparedTx = StellarSdk.rpc.assembleTransaction(tx, simResult).build();
  
  // 5. Sign with Freighter Wallet
  const unsignedXdr = preparedTx.toXDR();
  const signResult = await signTransaction(unsignedXdr, { networkPassphrase: TESTNET_PASSPHRASE, address: userPublicKey });
  if (signResult.error) {
    throw new Error(`Freighter signing failed: ${signResult.error}`);
  }
  if (!signResult.signedTxXdr) {
    throw new Error("Freighter did not return a signed transaction XDR.");
  }
  
  // 6. Submit signed XDR to Stellar network
  const signedTx = StellarSdk.TransactionBuilder.fromXDR(signResult.signedTxXdr, TESTNET_PASSPHRASE);
  const submitResult = await server.sendTransaction(signedTx);
  
  if (submitResult.status === "ERROR") {
    throw new Error(`Transaction submission error: ${submitResult.errorResult || "Unknown error"}`);
  }
  
  // 7. Poll for final confirmation
  const txHash = submitResult.hash;
  console.log("Transaction submitted. Hash:", txHash);
  
  let status = "PENDING";
  let retryCount = 0;
  while (status === "PENDING" || status === "NOT_FOUND") {
    if (retryCount > 25) {
      throw new Error(`Transaction polling timed out. Hash: ${txHash}`);
    }
    const result = await server.getTransaction(txHash);
    status = result.status;
    
    if (status === "SUCCESS") {
      return txHash;
    } else if (status === "FAILED") {
      throw new Error("Transaction failed on-chain.");
    }
    
    retryCount++;
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  
  return txHash;
}

// Concrete transaction functions to be consumed by the UI

export async function depositToVault(
  vaultId: string,
  amount: string,
  fromAddress: string
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(fromAddress, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(amount), { type: "i128" }),
  ];
  return invokeContractMethod(vaultId, "deposit", args, fromAddress);
}

export async function submitRequestToVault(
  vaultId: string,
  proposer: string,
  recipient: string,
  amount: string,
  description: string
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(proposer, { type: "address" }),
    StellarSdk.nativeToScVal(recipient, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(amount), { type: "i128" }),
    StellarSdk.nativeToScVal(description, { type: "string" }),
  ];
  return invokeContractMethod(vaultId, "submit_request", args, proposer);
}

export async function approveRequestInVault(
  vaultId: string,
  approver: string,
  requestId: number
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(approver, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" }),
  ];
  return invokeContractMethod(vaultId, "approve_request", args, approver);
}

export async function executeRequestInVault(
  vaultId: string,
  executor: string,
  requestId: number
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(executor, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" }),
  ];
  return invokeContractMethod(vaultId, "execute_request", args, executor);
}

export async function cancelRequestInVault(
  vaultId: string,
  canceller: string,
  requestId: number
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(canceller, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" }),
  ];
  return invokeContractMethod(vaultId, "cancel_request", args, canceller);
}

/**
 * Establishes a trustline for the mock USDC token
 */
export async function establishTrustline(userPublicKey: string): Promise<string> {
  const server = getRpcServer();
  const account = await server.getAccount(userPublicKey);
  const asset = new StellarSdk.Asset("USDC", CONTRACTS.adminAddress);
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(StellarSdk.Operation.changeTrust({ asset }))
    .setTimeout(120)
    .build();

  const unsignedXdr = tx.toXDR();
  const signResult = await signTransaction(unsignedXdr, { 
    networkPassphrase: TESTNET_PASSPHRASE, 
    address: userPublicKey 
  });
  
  if (signResult.error) {
    throw new Error(`Freighter signing failed: ${signResult.error}`);
  }
  if (!signResult.signedTxXdr) {
    throw new Error("Freighter did not return a signed transaction XDR.");
  }
  
  const signedTx = StellarSdk.TransactionBuilder.fromXDR(signResult.signedTxXdr, TESTNET_PASSPHRASE);
  const submitResult = await server.sendTransaction(signedTx);
  
  if (submitResult.status === "ERROR") {
    throw new Error(`Transaction submission error: ${submitResult.errorResult || "Unknown error"}`);
  }
  
  const txHash = submitResult.hash;
  console.log("Trustline transaction submitted. Hash:", txHash);
  
  let status = "PENDING";
  let retryCount = 0;
  while (status === "PENDING" || status === "NOT_FOUND") {
    if (retryCount > 25) {
      throw new Error(`Transaction polling timed out. Hash: ${txHash}`);
    }
    const result = await server.getTransaction(txHash);
    status = result.status;
    
    if (status === "SUCCESS") {
      return txHash;
    } else if (status === "FAILED") {
      throw new Error("Trustline transaction failed on-chain.");
    }
    
    retryCount++;
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  
  return txHash;
}

/**
 * Fetch native XLM balance of a Stellar account
 */
export async function fetchXlmBalance(address: string): Promise<string> {
  try {
    const response = await fetch(`https://horizon-testnet.stellar.org/accounts/${address}`);
    if (!response.ok) return "0";
    const data = await response.json();
    const nativeBalance = data.balances.find((b: any) => b.asset_type === "native");
    return nativeBalance ? nativeBalance.balance : "0";
  } catch (err) {
    console.error("Error fetching XLM balance:", err);
    return "0";
  }
}

/**
 * Sends a native XLM payment transaction on the Stellar Testnet signed with Freighter
 */
export async function sendXlmTransaction(
  fromAddress: string,
  toAddress: string,
  amount: string
): Promise<string> {
  const server = getRpcServer();
  const account = await server.getAccount(fromAddress);
  
  // Build native payment operation
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(
      StellarSdk.Operation.payment({
        destination: toAddress,
        asset: StellarSdk.Asset.native(),
        amount: amount,
      })
    )
    .setTimeout(120)
    .build();

  const unsignedXdr = tx.toXDR();
  const signResult = await signTransaction(unsignedXdr, { 
    networkPassphrase: TESTNET_PASSPHRASE, 
    address: fromAddress 
  });
  
  if (signResult.error) {
    throw new Error(`Freighter signing failed: ${signResult.error}`);
  }
  if (!signResult.signedTxXdr) {
    throw new Error("Freighter did not return a signed transaction XDR.");
  }
  
  const signedTx = StellarSdk.TransactionBuilder.fromXDR(signResult.signedTxXdr, TESTNET_PASSPHRASE);
  const submitResult = await server.sendTransaction(signedTx);
  
  if (submitResult.status === "ERROR") {
    throw new Error(`Transaction submission error: ${submitResult.errorResult || "Unknown error"}`);
  }
  
  const txHash = submitResult.hash;
  console.log("XLM payment transaction submitted. Hash:", txHash);
  
  let status = "PENDING";
  let retryCount = 0;
  while (status === "PENDING" || status === "NOT_FOUND") {
    if (retryCount > 25) {
      throw new Error(`Transaction polling timed out. Hash: ${txHash}`);
    }
    const result = await server.getTransaction(txHash);
    status = result.status;
    
    if (status === "SUCCESS") {
      return txHash;
    } else if (status === "FAILED") {
      throw new Error("XLM transaction failed on-chain.");
    }
    
    retryCount++;
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  
  return txHash;
}

/**
 * Fetch event logs from Soroban RPC for a contract
 */
export async function fetchContractEvents(contractId: string): Promise<any[]> {
  const server = getRpcServer();
  try {
    const latestLedgerRes = await server.getLatestLedger();
    const latestLedger = latestLedgerRes.sequence;
    const startLedger = Math.max(1, latestLedger - 1000); // last ~1000 ledgers (approx 1.5 hours)
    
    const eventsRes = await server.getEvents({
      startLedger: startLedger,
      filters: [
        {
          type: "contract",
          contractIds: [contractId],
        }
      ],
      limit: 15,
    });
    
    if (!eventsRes || !eventsRes.events) return [];
    
    return eventsRes.events.map((evt) => {
      let type = "event";
      let details = "Contract event";
      let user = contractId;
      
      try {
        const topics = evt.topic.map((t) => StellarSdk.scValToNative(t));
        const value = StellarSdk.scValToNative(evt.value);
        
        const eventName = topics[0]?.toString();
        if (eventName === "deposit") {
          type = "deposit";
          user = topics[1]?.toString() || user;
          details = `Deposited ${parseFloat(value.toString()).toLocaleString()} USDC into vault`;
        } else if (eventName === "request_submitted") {
          type = "submit_request";
          user = topics[1]?.toString() || user;
          details = `Created Spending Proposal #${value.toString()}`;
        } else if (eventName === "request_approved") {
          type = "approve_request";
          user = topics[1]?.toString() || user;
          details = `Approved Proposal #${value.toString()}`;
        } else if (eventName === "request_executed") {
          type = "execute_request";
          user = topics[1]?.toString() || user;
          details = `Executed Proposal #${value.toString()}`;
        } else if (eventName === "request_cancelled") {
          type = "cancel_request";
          user = topics[1]?.toString() || user;
          details = `Cancelled Proposal #${value.toString()}`;
        }
      } catch (err) {
        console.warn("Failed to parse event topics:", err);
      }
      
      return {
        id: evt.id,
        timestamp: Date.now(),
        type: type,
        user: user,
        details: details,
      };
    });
  } catch (err) {
    console.error("Failed to fetch contract events:", err);
    return [];
  }
}


