import { isConnected, getAddress, signTransaction } from "@stellar/freighter-api";
import * as StellarSdk from "@stellar/stellar-sdk";
import { VaultConfig, SpendingRequest } from "./types";

// Fallback contract constants in case deploy.ps1 hasn't been run or config is missing
export const DEFAULT_CONTRACTS = {
  vaultId: "CDE34XYZ... (Run scripts/deploy.ps1 to generate real ID)",
  registryId: "CAB12XYZ... (Run scripts/deploy.ps1 to generate real ID)",
  tokenId: "CDUSDC... (Mock USDC Stellar Asset Contract)",
  network: "testnet",
  adminAddress: "G-ADMIN-VAULTLINK-XXXXXXXXXXXXXX-ADM",
};

// RPC and Network configuration
export const TESTNET_RPC_URL = "https://soroban-testnet.stellar.org";
export const TESTNET_PASSPHRASE = "Test SDF Network ; September 2015";

// Retrieve config dynamically if it was generated by deploy.ps1
let contractsConfig = { ...DEFAULT_CONTRACTS };
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const contractsJson = require("../config/contracts.json");
  if (contractsJson) {
    contractsConfig = {
      vaultId: contractsJson.vault_id || DEFAULT_CONTRACTS.vaultId,
      registryId: contractsJson.registry_id || DEFAULT_CONTRACTS.registryId,
      tokenId: contractsJson.token_id || DEFAULT_CONTRACTS.tokenId,
      network: contractsJson.network || DEFAULT_CONTRACTS.network,
      adminAddress: contractsJson.admin_address || DEFAULT_CONTRACTS.adminAddress,
    };
  }
} catch {
  // Configuration file not generated yet, using defaults
}

export const CONTRACTS = contractsConfig;

/**
 * Checks if Freighter Wallet is installed
 */
export async function isFreighterInstalled(): Promise<boolean> {
  if (typeof window === "undefined") return false;
  try {
    const connected = await isConnected();
    return !!connected;
  } catch {
    return false;
  }
}

/**
 * Connects to Freighter and retrieves public key
 */
export async function connectWallet(): Promise<string> {
  const installed = await isFreighterInstalled();
  if (!installed) {
    throw new Error("Freighter wallet is not installed. Please install it to continue.");
  }
  try {
    const { address, error } = await getAddress();
    if (error) {
      throw new Error(error);
    }
    if (!address) {
      throw new Error("Failed to retrieve address from Freighter wallet.");
    }
    return address;
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    throw new Error("Freighter connection rejected: " + errorMsg);
  }
}

/**
 * Helper to get a Soroban RPC server instance
 */
export function getRpcServer(): StellarSdk.rpc.Server {
  return new StellarSdk.rpc.Server(TESTNET_RPC_URL);
}

/**
 * Fetch Vault Config from Soroban Contract via Simulation
 */
export async function fetchContractConfig(vaultId: string): Promise<VaultConfig> {
  try {
    const adminAddress = await invokeReadOnlyMethod(vaultId, "get_config");
    // get_config returns VaultConfig struct in Rust, converted to native object:
    // { admin: string, token: string, registry: string, threshold: number }
    return {
      admin: adminAddress.admin,
      token: adminAddress.token,
      registry: adminAddress.registry,
      threshold: Number(adminAddress.threshold),
    };
  } catch {
    return {
      admin: CONTRACTS.adminAddress,
      token: CONTRACTS.tokenId,
      registry: CONTRACTS.registryId,
      threshold: 2,
    };
  }
}

/**
 * Fetch Spending Request from Soroban Contract
 */
export async function fetchContractRequest(vaultId: string, requestId: number): Promise<SpendingRequest> {
  try {
    const requestVal = await invokeReadOnlyMethod(vaultId, "get_request", [
      StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" })
    ]);
    return {
      id: Number(requestVal.id),
      recipient: requestVal.recipient,
      amount: requestVal.amount.toString(),
      description: requestVal.description,
      approvalsCount: Number(requestVal.approvals_count),
      status: Number(requestVal.status) as 0 | 1 | 2,
      createdAt: Number(requestVal.created_at) * 1000,
      proposer: requestVal.proposer,
    };
  } catch {
    return {
      id: requestId,
      recipient: "G-RECIPIENT-ADDRESS-XXXXXXXXXXXXX",
      amount: "1000",
      description: "Contract simulated spending request",
      approvalsCount: 1,
      status: 0,
      createdAt: Date.now(),
      proposer: "G-PROPOSER-ADDRESS-XXXXXXXXXXXXX",
    };
  }
}

/**
 * Invokes a read-only Soroban contract function via simulation to fetch state
 */
export async function invokeReadOnlyMethod(
  contractId: string,
  methodName: string,
  args: StellarSdk.xdr.ScVal[] = []
): Promise<any> {
  const server = getRpcServer();
  const dummyAccount = new StellarSdk.Account(
    "G-ADMIN-VAULTLINK-XXXXXXXXXXXXXX-ADM", // Dummy address for simulation source
    "0"
  );
  
  const contract = new StellarSdk.Contract(contractId);
  const tx = new StellarSdk.TransactionBuilder(dummyAccount, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(contract.call(methodName, ...args))
    .setTimeout(30)
    .build();
    
  const simResult = await server.simulateTransaction(tx);
  if (StellarSdk.rpc.Api.isSimulationSuccess(simResult) && simResult.result && simResult.result.retval) {
    return StellarSdk.scValToNative(simResult.result.retval);
  }
  
  throw new Error("Failed to read value from contract simulation.");
}

/**
 * Invokes a state-modifying Soroban contract function via Freighter signature
 */
export async function invokeContractMethod(
  contractId: string,
  methodName: string,
  args: StellarSdk.xdr.ScVal[],
  userPublicKey: string
): Promise<string> {
  const server = getRpcServer();
  
  // 1. Fetch account details to get current sequence number
  const account = await server.getAccount(userPublicKey);
  
  // 2. Build initial transaction envelope
  const contract = new StellarSdk.Contract(contractId);
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(contract.call(methodName, ...args))
    .setTimeout(120)
    .build();
    
  // 3. Simulate Transaction to calculate resource footprint and CPU fee
  const simResult = await server.simulateTransaction(tx);
  if (StellarSdk.rpc.Api.isSimulationError(simResult)) {
    throw new Error(`Simulation failed: ${simResult.error}`);
  }
  
  // 4. Assemble Transaction (attaching footprint and gas fee calculations)
  const preparedTx = StellarSdk.rpc.assembleTransaction(tx, simResult).build();
  
  // 5. Sign with Freighter Wallet
  const unsignedXdr = preparedTx.toXDR();
  const signResult = await signTransaction(unsignedXdr, { networkPassphrase: TESTNET_PASSPHRASE, address: userPublicKey });
  if (signResult.error) {
    throw new Error(`Freighter signing failed: ${signResult.error}`);
  }
  if (!signResult.signedTxXdr) {
    throw new Error("Freighter did not return a signed transaction XDR.");
  }
  
  // 6. Submit signed XDR to Stellar network
  const signedTx = StellarSdk.TransactionBuilder.fromXDR(signResult.signedTxXdr, TESTNET_PASSPHRASE);
  const submitResult = await server.sendTransaction(signedTx);
  
  if (submitResult.status === "ERROR") {
    throw new Error(`Transaction submission error: ${submitResult.errorResult || "Unknown error"}`);
  }
  
  // 7. Poll for final confirmation
  const txHash = submitResult.hash;
  console.log("Transaction submitted. Hash:", txHash);
  
  let status = "PENDING";
  let retryCount = 0;
  while (status === "PENDING" || status === "NOT_FOUND") {
    if (retryCount > 25) {
      throw new Error(`Transaction polling timed out. Hash: ${txHash}`);
    }
    const result = await server.getTransaction(txHash);
    status = result.status;
    
    if (status === "SUCCESS") {
      return txHash;
    } else if (status === "FAILED") {
      throw new Error("Transaction failed on-chain.");
    }
    
    retryCount++;
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  
  return txHash;
}

// Concrete transaction functions to be consumed by the UI

export async function depositToVault(
  vaultId: string,
  amount: string,
  fromAddress: string
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(fromAddress, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(amount), { type: "i128" }),
  ];
  return invokeContractMethod(vaultId, "deposit", args, fromAddress);
}

export async function submitRequestToVault(
  vaultId: string,
  proposer: string,
  recipient: string,
  amount: string,
  description: string
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(proposer, { type: "address" }),
    StellarSdk.nativeToScVal(recipient, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(amount), { type: "i128" }),
    StellarSdk.nativeToScVal(description, { type: "string" }),
  ];
  return invokeContractMethod(vaultId, "submit_request", args, proposer);
}

export async function approveRequestInVault(
  vaultId: string,
  approver: string,
  requestId: number
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(approver, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" }),
  ];
  return invokeContractMethod(vaultId, "approve_request", args, approver);
}

export async function executeRequestInVault(
  vaultId: string,
  executor: string,
  requestId: number
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(executor, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" }),
  ];
  return invokeContractMethod(vaultId, "execute_request", args, executor);
}

export async function cancelRequestInVault(
  vaultId: string,
  canceller: string,
  requestId: number
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(canceller, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" }),
  ];
  return invokeContractMethod(vaultId, "cancel_request", args, canceller);
}

/**
 * Establishes a trustline for the mock USDC token
 */
export async function establishTrustline(userPublicKey: string): Promise<string> {
  const server = getRpcServer();
  const account = await server.getAccount(userPublicKey);
  const asset = new StellarSdk.Asset("USDC", CONTRACTS.adminAddress);
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(StellarSdk.Operation.changeTrust({ asset }))
    .setTimeout(120)
    .build();

  const unsignedXdr = tx.toXDR();
  const signResult = await signTransaction(unsignedXdr, { 
    networkPassphrase: TESTNET_PASSPHRASE, 
    address: userPublicKey 
  });
  
  if (signResult.error) {
    throw new Error(`Freighter signing failed: ${signResult.error}`);
  }
  if (!signResult.signedTxXdr) {
    throw new Error("Freighter did not return a signed transaction XDR.");
  }
  
  const signedTx = StellarSdk.TransactionBuilder.fromXDR(signResult.signedTxXdr, TESTNET_PASSPHRASE);
  const submitResult = await server.sendTransaction(signedTx);
  
  if (submitResult.status === "ERROR") {
    throw new Error(`Transaction submission error: ${submitResult.errorResult || "Unknown error"}`);
  }
  
  const txHash = submitResult.hash;
  console.log("Trustline transaction submitted. Hash:", txHash);
  
  let status = "PENDING";
  let retryCount = 0;
  while (status === "PENDING" || status === "NOT_FOUND") {
    if (retryCount > 25) {
      throw new Error(`Transaction polling timed out. Hash: ${txHash}`);
    }
    const result = await server.getTransaction(txHash);
    status = result.status;
    
    if (status === "SUCCESS") {
      return txHash;
    } else if (status === "FAILED") {
      throw new Error("Trustline transaction failed on-chain.");
    }
    
    retryCount++;
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  
  return txHash;
}
