import * as StellarSdk from "@stellar/stellar-sdk";
import { VaultConfig, SpendingRequest, ActivityLog, Comment, VaultRules, ContributionPlan } from "./types";
import { getWalletProvider, WalletProviderId } from "./wallet-adapters";

// Fallback contract constants in case deploy.ps1 hasn't been run or config is missing
export const DEFAULT_CONTRACTS = {
  vaultId: "CDE34XYZ... (Run scripts/deploy.ps1 to generate real ID)",
  registryId: "CAB12XYZ... (Run scripts/deploy.ps1 to generate real ID)",
  tokenId: "CDUSDC... (Mock USDC Stellar Asset Contract)",
  network: "testnet",
  adminAddress: "GACYFFEF6TV4MNCRW5LYZ57PO6V3CAVZMGYBEHD4MG6IPYVXENE4XJQO",
};

// RPC and Network configuration
export const TESTNET_RPC_URL = "https://soroban-testnet.stellar.org";
export const TESTNET_PASSPHRASE = "Test SDF Network ; September 2015";

// Retrieve config dynamically if it was generated by deploy.ps1
let contractsConfig = { ...DEFAULT_CONTRACTS };
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const contractsJson = require("../config/contracts.json");
  if (contractsJson) {
    contractsConfig = {
      vaultId: contractsJson.vault_id || DEFAULT_CONTRACTS.vaultId,
      registryId: contractsJson.registry_id || DEFAULT_CONTRACTS.registryId,
      tokenId: contractsJson.token_id || DEFAULT_CONTRACTS.tokenId,
      network: contractsJson.network || DEFAULT_CONTRACTS.network,
      adminAddress: contractsJson.admin_address || DEFAULT_CONTRACTS.adminAddress,
    };
  }
} catch {
  // Configuration file not generated yet, using defaults
}

export const CONTRACTS = contractsConfig;

/**
 * Checks if Freighter Wallet is installed (backward compat)
 */
export async function isFreighterInstalled(): Promise<boolean> {
  if (typeof window === "undefined") return false;
  try {
    const provider = getWalletProvider("freighter");
    return await provider.isAvailable();
  } catch {
    return false;
  }
}

/**
 * Connects to a wallet and retrieves public key
 */
export async function connectWallet(providerId: WalletProviderId = "freighter"): Promise<string> {
  const provider = getWalletProvider(providerId);
  const available = await provider.isAvailable();
  if (!available) {
    throw new Error(`${provider.name} wallet is not installed. Please install it to continue.`);
  }
  try {
    return await provider.connect();
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    throw new Error(`${provider.name} connection rejected: ${errorMsg}`);
  }
}

/**
 * Signs a transaction using the specified wallet provider
 */
export async function signWithWallet(
  xdr: string,
  userPublicKey: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const provider = getWalletProvider(providerId);
  const signResult = await provider.signTransaction(xdr, {
    networkPassphrase: TESTNET_PASSPHRASE,
    address: userPublicKey,
  });
  if (signResult.error) {
    throw new Error(`${provider.name} signing failed: ${signResult.error}`);
  }
  if (!signResult.signedTxXdr) {
    throw new Error(`${provider.name} did not return a signed transaction XDR.`);
  }
  return signResult.signedTxXdr;
}

/**
 * Helper to get a Soroban RPC server instance
 */
export function getRpcServer(): StellarSdk.rpc.Server {
  return new StellarSdk.rpc.Server(TESTNET_RPC_URL);
}

/**
 * Fetch Vault Config from Soroban Contract via Simulation
 */
export async function fetchContractConfig(vaultId: string): Promise<VaultConfig> {
  try {
    const result = await invokeReadOnlyMethod(vaultId, "get_config");
    // get_config returns VaultConfig struct in Rust, converted to native object:
    // { admin, token, registry, threshold, name, purpose }
    const cfg = result as Record<string, string | number>;
    return {
      admin: String(cfg.admin),
      token: String(cfg.token),
      registry: String(cfg.registry),
      threshold: Number(cfg.threshold),
      name: cfg.name !== undefined ? String(cfg.name) : "Team Treasury",
      purpose: cfg.purpose !== undefined ? String(cfg.purpose) : "Shared multi-sig fund for group expenses",
    };
  } catch {
    return {
      admin: CONTRACTS.adminAddress,
      token: CONTRACTS.tokenId,
      registry: CONTRACTS.registryId,
      threshold: 2,
      name: "Team Treasury",
      purpose: "Shared multi-sig fund for group expenses",
    };
  }
}

/**
 * Fetch Spending Request from Soroban Contract
 */
export async function fetchContractRequest(vaultId: string, requestId: number): Promise<SpendingRequest> {
  try {
    const requestVal = await invokeReadOnlyMethod(vaultId, "get_request", [
      StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" })
    ]);
    const req = requestVal as Record<string, string | number>;
    return {
      id: Number(req.id),
      recipient: String(req.recipient),
      amount: String(req.amount),
      category: req.category !== undefined ? String(req.category) : "Other",
      description: String(req.description),
      receiptUrl: req.receipt_url !== undefined ? String(req.receipt_url) : "",
      approvalsCount: Number(req.approvals_count),
      status: Number(req.status) as 0 | 1 | 2,
      createdAt: Number(req.created_at) * 1000,
      proposer: String(req.proposer),
    };
  } catch {
    return {
      id: requestId,
      recipient: "G-RECIPIENT-ADDRESS-XXXXXXXXXXXXX",
      amount: "1000",
      category: "Operations",
      description: "Contract simulated spending request",
      receiptUrl: "",
      approvalsCount: 1,
      status: 0,
      createdAt: Date.now(),
      proposer: "G-PROPOSER-ADDRESS-XXXXXXXXXXXXX",
    };
  }
}

/**
 * Fetch Vault Balance from Soroban Contract via Simulation
 */
export async function fetchVaultBalance(vaultId: string): Promise<string> {
  try {
    const balance = await invokeReadOnlyMethod(vaultId, "get_vault_balance");
    return balance.toString();
  } catch (err) {
    console.error("Error fetching vault balance:", err);
    return "0";
  }
}

/**
 * Fetch all spending requests from the Vault Contract
 */
export async function fetchContractRequests(vaultId: string): Promise<SpendingRequest[]> {
  try {
    const countVal = await invokeReadOnlyMethod(vaultId, "get_request_count");
    const count = Number(countVal);
    const requests: SpendingRequest[] = [];
    
    for (let i = 1; i <= count; i++) {
      try {
        const req = await fetchContractRequest(vaultId, i);
        // Filter out fallback requests if possible (we verify id is retrieved)
        requests.push(req);
      } catch (err) {
        console.error(`Error fetching request #${i}:`, err);
      }
    }
    
    return requests.reverse(); // Newest first
  } catch (err) {
    console.error("Error fetching request count:", err);
    return [];
  }
}

/**
 * Fetch token balance for a given address
 */
export async function fetchTokenBalance(tokenId: string, address: string): Promise<string> {
  try {
    const balance = await invokeReadOnlyMethod(tokenId, "balance", [
      StellarSdk.nativeToScVal(address, { type: "address" })
    ]);
    return balance.toString();
  } catch (err) {
    console.error("Error fetching token balance:", err);
    return "0";
  }
}

interface HorizonBalance {
  asset_type: string;
  balance: string;
}

interface HorizonAccountResponse {
  balances: HorizonBalance[];
}

/**
 * Invokes a read-only Soroban contract function via simulation to fetch state
 */
export async function invokeReadOnlyMethod(
  contractId: string,
  methodName: string,
  args: StellarSdk.xdr.ScVal[] = []
): Promise<Record<string, unknown>> {
  const server = getRpcServer();
  const dummyAccount = new StellarSdk.Account(
    CONTRACTS.adminAddress && CONTRACTS.adminAddress.startsWith("G") && CONTRACTS.adminAddress.length === 56
      ? CONTRACTS.adminAddress
      : "GACYFFEF6TV4MNCRW5LYZ57PO6V3CAVZMGYBEHD4MG6IPYVXENE4XJQO", // Dummy address for simulation source
    "0"
  );
  
  const contract = new StellarSdk.Contract(contractId);
  const tx = new StellarSdk.TransactionBuilder(dummyAccount, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(contract.call(methodName, ...args))
    .setTimeout(30)
    .build();
    
  const simResult = await server.simulateTransaction(tx);
  if (StellarSdk.rpc.Api.isSimulationSuccess(simResult) && simResult.result && simResult.result.retval) {
    return StellarSdk.scValToNative(simResult.result.retval) as Record<string, unknown>;
  }
  
  throw new Error("Failed to read value from contract simulation.");
}

/**
 * Invokes a state-modifying Soroban contract function via wallet signature
 */
export async function invokeContractMethod(
  contractId: string,
  methodName: string,
  args: StellarSdk.xdr.ScVal[],
  userPublicKey: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const server = getRpcServer();
  
  // 1. Fetch account details to get current sequence number
  const account = await server.getAccount(userPublicKey);
  
  // 2. Build initial transaction envelope
  const contract = new StellarSdk.Contract(contractId);
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(contract.call(methodName, ...args))
    .setTimeout(120)
    .build();
    
  // 3. Simulate Transaction to calculate resource footprint and CPU fee
  const simResult = await server.simulateTransaction(tx);
  if (StellarSdk.rpc.Api.isSimulationError(simResult)) {
    throw new Error(`Simulation failed: ${simResult.error}`);
  }
  
  // 4. Assemble Transaction (attaching footprint and gas fee calculations)
  const preparedTx = StellarSdk.rpc.assembleTransaction(tx, simResult).build();
  
  // 5. Sign with Wallet
  const unsignedXdr = preparedTx.toXDR();
  const signedXdr = await signWithWallet(unsignedXdr, userPublicKey, providerId);
  
  // 6. Submit signed XDR to Stellar network
  const signedTx = StellarSdk.TransactionBuilder.fromXDR(signedXdr, TESTNET_PASSPHRASE);
  const submitResult = await server.sendTransaction(signedTx);
  
  if (submitResult.status === "ERROR") {
    throw new Error(`Transaction submission error: ${submitResult.errorResult || "Unknown error"}`);
  }
  
  // 7. Poll for final confirmation
  const txHash = submitResult.hash;
  console.log("Transaction submitted. Hash:", txHash);
  
  let status = "PENDING";
  let retryCount = 0;
  while (status === "PENDING" || status === "NOT_FOUND") {
    if (retryCount > 25) {
      throw new Error(`Transaction polling timed out. Hash: ${txHash}`);
    }
    const result = await server.getTransaction(txHash);
    status = result.status;
    
    if (status === "SUCCESS") {
      return txHash;
    } else if (status === "FAILED") {
      throw new Error("Transaction failed on-chain.");
    }
    
    retryCount++;
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  
  return txHash;
}

// Concrete transaction functions to be consumed by the UI

export async function depositToVault(
  vaultId: string,
  amount: string,
  fromAddress: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(fromAddress, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(amount), { type: "i128" }),
  ];
  return invokeContractMethod(vaultId, "deposit", args, fromAddress, providerId);
}

/**
 * Emergency pause toggle (Owner only). While paused, withdrawals cannot execute.
 */
export async function setVaultPaused(
  vaultId: string,
  caller: string,
  paused: boolean,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(caller, { type: "address" }),
    StellarSdk.nativeToScVal(paused),
  ];
  return invokeContractMethod(vaultId, "set_paused", args, caller, providerId);
}

export async function fetchVaultPaused(vaultId: string): Promise<boolean> {
  try {
    const result = await invokeReadOnlyMethod(vaultId, "is_paused");
    return String(result) === "true";
  } catch (err) {
    console.error("Error fetching vault pause state:", err);
    return false;
  }
}

/**
 * Invite members (Owner only): upsert a wallet address with a role.
 */
export async function setMemberRoleInVault(
  vaultId: string,
  caller: string,
  member: string,
  role: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(caller, { type: "address" }),
    StellarSdk.nativeToScVal(member, { type: "address" }),
    StellarSdk.nativeToScVal(role, { type: "string" }),
  ];
  return invokeContractMethod(vaultId, "set_member_role", args, caller, providerId);
}

export async function fetchMembers(vaultId: string): Promise<string[]> {
  try {
    const result = await invokeReadOnlyMethod(vaultId, "get_members");
    return Array.isArray(result) ? result.map(String) : [];
  } catch (err) {
    console.error("Error fetching members:", err);
    return [];
  }
}

/**
 * Comment on a pending spending request (any member).
 */
export async function addCommentToVault(
  vaultId: string,
  commenter: string,
  requestId: number,
  text: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(commenter, { type: "address" }),
    StellarSdk.nativeToScVal(requestId, { type: "u64" }),
    StellarSdk.nativeToScVal(text, { type: "string" }),
  ];
  return invokeContractMethod(vaultId, "add_comment", args, commenter, providerId);
}

export async function fetchContractComments(vaultId: string, requestId: number): Promise<Comment[]> {
  try {
    const result = await invokeReadOnlyMethod(vaultId, "get_comments", [
      StellarSdk.nativeToScVal(requestId, { type: "u64" })
    ]);
    const arr = Array.isArray(result) ? result : [];
    return arr.map((c) => {
      const rec = c as Record<string, unknown>;
      return {
        author: String(rec.author),
        text: String(rec.text),
        timestamp: Number(rec.created_at) * 1000,
      };
    });
  } catch (err) {
    console.error("Error fetching comments:", err);
    return [];
  }
}

/**
 * Owner-configurable spending rules incl. the monthly contribution target.
 */
export async function fetchRules(vaultId: string): Promise<VaultRules> {
  const defaults: VaultRules = { maxRequestAmount: "0", blockedCategories: [], monthlyTarget: "0", categoryCaps: {} };
  try {
    const r = await invokeReadOnlyMethod(vaultId, "get_rules");
    const caps: Record<string, string> = {};
    if (r.category_caps && typeof r.category_caps === "object") {
      for (const [k, v] of Object.entries(r.category_caps as Record<string, unknown>)) {
        caps[k] = String(v);
      }
    }
    return {
      maxRequestAmount: String(r.max_request_amount ?? defaults.maxRequestAmount),
      blockedCategories: Array.isArray(r.blocked_categories) ? r.blocked_categories.map(String) : [],
      monthlyTarget: String(r.monthly_target ?? defaults.monthlyTarget),
      categoryCaps: caps,
    };
  } catch (err) {
    console.error("Error fetching rules:", err);
    return defaults;
  }
}

export async function fetchContribution(vaultId: string, member: string, period: number): Promise<string> {
  try {
    const result = await invokeReadOnlyMethod(vaultId, "get_contribution", [
      StellarSdk.nativeToScVal(member, { type: "address" }),
      StellarSdk.nativeToScVal(period, { type: "u32" }),
    ]);
    return String(result ?? "0");
  } catch (err) {
    console.error("Error fetching contribution:", err);
    return "0";
  }
}

export async function fetchMemberRole(vaultId: string, member: string): Promise<string> {
  const result = await invokeReadOnlyMethod(vaultId, "get_member_role", [
    StellarSdk.nativeToScVal(member, { type: "address" })
  ]);
  return String(result);
}

/**
 * Rule engine configuration (Owner only), incl. monthly contribution target
 * and per-category budget caps.
 */
export async function setRulesInVault(
  vaultId: string,
  caller: string,
  maxRequestAmount: string,
  blockedCategories: string[],
  monthlyTarget: string,
  categoryCaps: Record<string, string> = {},
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const caps: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(categoryCaps)) {
    caps[k] = nativeToScValBigInt(v);
  }
  const args = [
    StellarSdk.nativeToScVal(caller, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(maxRequestAmount || "0"), { type: "i128" }),
    StellarSdk.nativeToScVal(blockedCategories),
    StellarSdk.nativeToScVal(BigInt(monthlyTarget || "0"), { type: "i128" }),
    StellarSdk.nativeToScVal(caps),
  ];
  return invokeContractMethod(vaultId, "set_rules", args, caller, providerId);
}

const nativeToScValBigInt = (v: string): StellarSdk.xdr.ScVal =>
  StellarSdk.nativeToScVal(BigInt(v || "0"), { type: "i128" });

/**
 * Recurring contributions (feature: recurring contributions).
 */
export async function setContributionPlanInVault(
  vaultId: string,
  caller: string,
  amount: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(caller, { type: "address" }),
    nativeToScValBigInt(amount),
  ];
  return invokeContractMethod(vaultId, "set_contribution_plan", args, caller, providerId);
}

export async function cancelContributionPlanInVault(
  vaultId: string,
  caller: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [StellarSdk.nativeToScVal(caller, { type: "address" })];
  return invokeContractMethod(vaultId, "cancel_contribution_plan", args, caller, providerId);
}

export async function fetchContributionPlan(
  vaultId: string,
  member: string
): Promise<ContributionPlan | null> {
  try {
    const result = await invokeReadOnlyMethod(vaultId, "get_contribution_plan", [
      StellarSdk.nativeToScVal(member, { type: "address" }),
    ]);
    if (!result) return null;
    const rec = result as Record<string, unknown>;
    return {
      subscriber: String(rec.subscriber),
      amount: String(rec.amount),
      active: Boolean(rec.active),
      lastPeriod: Number(rec.last_period ?? 0),
    };
  } catch (err) {
    console.error("Error fetching contribution plan:", err);
    return null;
  }
}

/** Charges all due recurring plans; anyone may call it. Returns tx hash. */
export async function runDueContributionsInVault(
  vaultId: string,
  caller: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  return invokeContractMethod(vaultId, "run_due_contributions", [], caller, providerId);
}

/**
 * Grants the vault a token allowance (SAC approve) so recurring monthly
 * charges can be pulled automatically (feature: recurring contributions).
 */
export async function approveTokenAllowance(
  tokenId: string,
  from: string,
  spender: string,
  amount: string,
  expirationLedger: number,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(from, { type: "address" }),
    StellarSdk.nativeToScVal(spender, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(amount || "0"), { type: "i128" }),
    StellarSdk.nativeToScVal(expirationLedger, { type: "u32" }),
  ];
  return invokeContractMethod(tokenId, "approve", args, from, providerId);
}

export async function submitRequestToVault(
  vaultId: string,
  proposer: string,
  recipient: string,
  amount: string,
  category: string,
  description: string,
  receiptUrl: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(proposer, { type: "address" }),
    StellarSdk.nativeToScVal(recipient, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(amount), { type: "i128" }),
    StellarSdk.nativeToScVal(category, { type: "string" }),
    StellarSdk.nativeToScVal(description, { type: "string" }),
    StellarSdk.nativeToScVal(receiptUrl, { type: "string" }),
  ];
  return invokeContractMethod(vaultId, "submit_request", args, proposer, providerId);
}

export async function approveRequestInVault(
  vaultId: string,
  approver: string,
  requestId: number,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(approver, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" }),
  ];
  return invokeContractMethod(vaultId, "approve_request", args, approver, providerId);
}

export async function executeRequestInVault(
  vaultId: string,
  executor: string,
  requestId: number,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(executor, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" }),
  ];
  return invokeContractMethod(vaultId, "execute_request", args, executor, providerId);
}

export async function cancelRequestInVault(
  vaultId: string,
  canceller: string,
  requestId: number,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const args = [
    StellarSdk.nativeToScVal(canceller, { type: "address" }),
    StellarSdk.nativeToScVal(BigInt(requestId), { type: "u64" }),
  ];
  return invokeContractMethod(vaultId, "cancel_request", args, canceller, providerId);
}

/**
 * Establishes a trustline for the mock USDC token
 */
export async function establishTrustline(
  userPublicKey: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const server = getRpcServer();
  const account = await server.getAccount(userPublicKey);
  const asset = new StellarSdk.Asset("USDC", CONTRACTS.adminAddress);
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(StellarSdk.Operation.changeTrust({ asset }))
    .setTimeout(120)
    .build();

  const unsignedXdr = tx.toXDR();
  const signedXdr = await signWithWallet(unsignedXdr, userPublicKey, providerId);
  
  const signedTx = StellarSdk.TransactionBuilder.fromXDR(signedXdr, TESTNET_PASSPHRASE);
  const submitResult = await server.sendTransaction(signedTx);
  
  if (submitResult.status === "ERROR") {
    throw new Error(`Transaction submission error: ${submitResult.errorResult || "Unknown error"}`);
  }
  
  const txHash = submitResult.hash;
  console.log("Trustline transaction submitted. Hash:", txHash);
  
  let status = "PENDING";
  let retryCount = 0;
  while (status === "PENDING" || status === "NOT_FOUND") {
    if (retryCount > 25) {
      throw new Error(`Transaction polling timed out. Hash: ${txHash}`);
    }
    const result = await server.getTransaction(txHash);
    status = result.status;
    
    if (status === "SUCCESS") {
      return txHash;
    } else if (status === "FAILED") {
      throw new Error("Trustline transaction failed on-chain.");
    }
    
    retryCount++;
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  
  return txHash;
}

/**
 * Fetch native XLM balance of a Stellar account
 */
export async function fetchXlmBalance(address: string): Promise<string> {
  try {
    const response = await fetch(`https://horizon-testnet.stellar.org/accounts/${address}`);
    if (!response.ok) return "0";
    const data: HorizonAccountResponse = await response.json();
    const nativeBalance = data.balances.find((b) => b.asset_type === "native");
    return nativeBalance ? nativeBalance.balance : "0";
  } catch (err) {
    console.error("Error fetching XLM balance:", err);
    return "0";
  }
}

/**
 * Sends a native XLM payment transaction on the Stellar Testnet signed via wallet
 */
export async function sendXlmTransaction(
  fromAddress: string,
  toAddress: string,
  amount: string,
  providerId: WalletProviderId = "freighter"
): Promise<string> {
  const server = getRpcServer();
  const account = await server.getAccount(fromAddress);
  
  // Build native payment operation
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: "100",
    networkPassphrase: TESTNET_PASSPHRASE,
  })
    .addOperation(
      StellarSdk.Operation.payment({
        destination: toAddress,
        asset: StellarSdk.Asset.native(),
        amount: amount,
      })
    )
    .setTimeout(120)
    .build();

  const unsignedXdr = tx.toXDR();
  const signedXdr = await signWithWallet(unsignedXdr, fromAddress, providerId);
  
  const signedTx = StellarSdk.TransactionBuilder.fromXDR(signedXdr, TESTNET_PASSPHRASE);
  const submitResult = await server.sendTransaction(signedTx);
  
  if (submitResult.status === "ERROR") {
    throw new Error(`Transaction submission error: ${submitResult.errorResult || "Unknown error"}`);
  }
  
  const txHash = submitResult.hash;
  console.log("XLM payment transaction submitted. Hash:", txHash);
  
  let status = "PENDING";
  let retryCount = 0;
  while (status === "PENDING" || status === "NOT_FOUND") {
    if (retryCount > 25) {
      throw new Error(`Transaction polling timed out. Hash: ${txHash}`);
    }
    const result = await server.getTransaction(txHash);
    status = result.status;
    
    if (status === "SUCCESS") {
      return txHash;
    } else if (status === "FAILED") {
      throw new Error("XLM transaction failed on-chain.");
    }
    
    retryCount++;
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  
  return txHash;
}

/**
 * Fetch event logs from Soroban RPC for a contract
 */
export async function fetchContractEvents(contractId: string): Promise<ActivityLog[]> {
  const server = getRpcServer();
  try {
    const latestLedgerRes = await server.getLatestLedger();
    const latestLedger = latestLedgerRes.sequence;
    const startLedger = Math.max(1, latestLedger - 1000); // last ~1000 ledgers (approx 1.5 hours)
    
    const eventsRes = await server.getEvents({
      startLedger: startLedger,
      filters: [
        {
          type: "contract",
          contractIds: [contractId],
        }
      ],
      limit: 15,
    });
    
    if (!eventsRes || !eventsRes.events) return [];
    
    return eventsRes.events.map((evt) => {
      let type = "event";
      let details = "Contract event";
      let user = contractId;
      
      try {
        const topics = evt.topic.map((t) => StellarSdk.scValToNative(t));
        const value = StellarSdk.scValToNative(evt.value);
        
        const eventName = topics[0]?.toString();
        if (eventName === "deposit") {
          type = "deposit";
          user = topics[1]?.toString() || user;
          details = `Deposited ${parseFloat(value.toString()).toLocaleString()} USDC into vault`;
        } else if (eventName === "request_submitted") {
          type = "submit_request";
          user = topics[1]?.toString() || user;
          details = `Created Spending Proposal #${value.toString()}`;
        } else if (eventName === "request_approved") {
          type = "approve_request";
          user = topics[1]?.toString() || user;
          details = `Approved Proposal #${value.toString()}`;
        } else if (eventName === "request_executed") {
          type = "execute_request";
          user = topics[1]?.toString() || user;
          details = `Executed Proposal #${value.toString()}`;
        } else if (eventName === "request_cancelled") {
          type = "cancel_request";
          user = topics[1]?.toString() || user;
          details = `Cancelled Proposal #${value.toString()}`;
        }
      } catch (err) {
        console.warn("Failed to parse event topics:", err);
      }
      
      return {
        id: evt.id,
        timestamp: Date.now(),
        type: type,
        user: user,
        details: details,
      };
    });
  } catch (err) {
    console.error("Failed to fetch contract events:", err);
    return [];
  }
}


